# each line is 3 integers separated by a space - (max temp, fan speed, pump level)
# fan speed is up to 90, pump level 0-off, 1 to 4 - on, larger number means more pumping power.
60 0 0
75 30 1
80 45 2
85 60 3
999 90 4